#    404 - Lost in Translation
#    (c) 2025 - Ronan Le Meillat - SCTG Development
#    
#    MIT License
#    
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#    furnished to do so, subject to the following conditions:
#    
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#    
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

name: Create Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install minification tools
        run: |
          npm install -g terser html-minifier

      - name: Minify HTML and inline JavaScript
        run: |
          # Create a temporary directory for minified files
          mkdir -p dist
          
          # Minify HTML with inline JavaScript and CSS
          html-minifier \
            --collapse-whitespace \
            --remove-comments \
            --minify-css \
            --minify-js \
            --remove-optional-tags \
            --remove-redundant-attributes \
            --remove-script-type-attributes \
            --remove-style-link-type-attributes \
            --use-short-doctype \
            index.html > dist/index.html

      - name: Create zip file
        run: |
          cd dist
          zip ../404-page.zip index.html
          cd ..

      - name: Delete existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete the existing 'last' release if it exists
          gh release delete last --yes || true
          # Delete the tag if it exists
          git push --delete origin last || true

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create last \
            404-page.zip \
            --title "Latest Release" \
            --notes "Automatically generated release containing the 404 page. This release is updated on every push to the main branch. Perfect for deploying to Cloudflare Pages or any static hosting service."

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: 404-page
          path: 404-page.zip
          retention-days: 90

      - name: Upload minified files artifact
        uses: actions/upload-artifact@v4
        with:
          name: pages-files
          path: dist/
          retention-days: 1

  deploy-pages:
    runs-on: ubuntu-latest
    needs: release
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download minified files
        uses: actions/download-artifact@v4
        with:
          name: pages-files
          path: pages-build-dir

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'pages-build-dir'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
